import abjad


metadata = abjad.OrderedDict(
    [
        ('duration', "0'55''"),
        ('final_measure_number', 141),
        ('first_measure_number', 111),
        ('segment_name', 'D'),
        ('segment_number', 5),
        ('start_clock_time', "2'09''"),
        ('stop_clock_time', "3'04''"),
        (
            'time_signatures',
            [
                '10/16',
                '5/16',
                '7/22',
                '1/1',
                '3/16',
                '13/16',
                '10/16',
                '5/16',
                '7/22',
                '1/1',
                '3/16',
                '13/16',
                '10/16',
                '5/16',
                '7/22',
                '1/1',
                '3/16',
                '13/16',
                '10/16',
                '5/16',
                '7/22',
                '1/1',
                '4/4',
                '4/4',
                '4/4',
                '3/16',
                '13/16',
                '5/22',
                '8/16',
                '7/20',
                '6/22',
                ],
            ),
        ]
    )
