import abjad


metadata = abjad.OrderedDict(
    [
        ('duration', "0'29''"),
        ('final_measure_number', 310),
        ('first_measure_number', 277),
        ('segment_name', 'J'),
        ('segment_number', 11),
        ('start_clock_time', "1'05''"),
        ('stop_clock_time', "1'34''"),
        (
            'time_signatures',
            [
                '1/4',
                '1/4',
                '1/4',
                '1/4',
                '1/4',
                '1/4',
                '1/4',
                '1/4',
                '1/4',
                '1/4',
                '1/4',
                '1/4',
                '1/4',
                '1/4',
                '4/16',
                '4/18',
                '11/16',
                '4/22',
                '1/4',
                '1/4',
                '1/4',
                '10/16',
                '5/16',
                '8/5',
                '1/4',
                '1/4',
                '1/4',
                '1/4',
                '1/4',
                '7/22',
                '3/16',
                '13/16',
                '5/22',
                '12/5',
                ],
            ),
        ]
    )
