import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Skips',
                'Music_Context',
                'Clarinet_Music_Staff',
                'Clarinet_Music_Voice',
                ],
            ),
        ('duration', "0'54''"),
        ('first_measure_number', 311),
        ('last_measure_number', 355),
        (
            'persistent_indicators',
            abjad.OrderedDict(
                [
                    (
                        'Clarinet_Music_Staff',
                        [
                            abjad.Momento(
                                context='Clarinet_Music_Voice',
                                manifest='instruments',
                                value='BassClarinet',
                                ),
                            abjad.Momento(
                                context='Clarinet_Music_Voice',
                                prototype='abjad.Clef',
                                value='treble',
                                ),
                            ],
                        ),
                    (
                        'Clarinet_Music_Voice',
                        [
                            abjad.Momento(
                                context='Clarinet_Music_Voice',
                                prototype='abjad.Dynamic',
                                value='ff',
                                ),
                            ],
                        ),
                    (
                        'Score',
                        [
                            abjad.Momento(
                                context='Global_Skips',
                                manifest='metronome_marks',
                                value='55',
                                ),
                            abjad.Momento(
                                context='Global_Skips',
                                prototype='abjad.TimeSignature',
                                value='3/16',
                                ),
                            ],
                        ),
                    ]
                ),
            ),
        ('segment_name', 'K'),
        ('segment_number', 12),
        (
            'sounds_during_segment',
            abjad.OrderedDict(
                [
                    ('Clarinet_Music_Voice', True),
                    ]
                ),
            ),
        ('start_clock_time', "1'33''"),
        ('stop_clock_time', "2'27''"),
        (
            'time_signatures',
            [
                '1/4',
                '1/4',
                '1/4',
                '1/1',
                '8/16',
                '7/20',
                '1/4',
                '1/4',
                '1/4',
                '1/4',
                '1/4',
                '6/22',
                '3/20',
                '11/16',
                '4/22',
                '8/5',
                '10/16',
                '4/16',
                '1/4',
                '1/4',
                '1/4',
                '7/22',
                '4/16',
                '1/4',
                '1/4',
                '1/4',
                '1/4',
                '1/4',
                '11/16',
                '4/22',
                '8/5',
                '10/16',
                '4/18',
                '7/22',
                '5/18',
                '12/16',
                '3/18',
                '8/16',
                '3/20',
                '2/3',
                '6/18',
                '7/20',
                '12/5',
                '4/3',
                '3/16',
                ],
            ),
        ]
    )
