import abjad


metadata = abjad.OrderedDict(
    [
        (
            "bol_measure_numbers",
            [384, 388, 393, 399, 405, 410, 415],
        ),
        ("duration", "2'35''"),
        ("final_measure_number", 417),
        ("first_measure_number", 384),
        ("segment_name", "N"),
        ("segment_number", 15),
        ("start_clock_time", "4'39''"),
        ("stop_clock_time", "7'14''"),
        (
            "time_signatures",
            [
                "4/4",
                "7/4",
                "4/4",
                "12/5",
                "4/4",
                "5/4",
                "4/4",
                "4/4",
                "8/4",
                "4/4",
                "4/3",
                "4/4",
                "4/4",
                "7/4",
                "2/3",
                "4/4",
                "4/4",
                "5/4",
                "4/4",
                "4/4",
                "7/4",
                "12/5",
                "4/4",
                "4/4",
                "5/4",
                "4/4",
                "4/4",
                "8/4",
                "4/4",
                "4/4",
                "4/4",
                "7/4",
                "4/4",
                "4/4",
            ],
        ),
    ]
)
